version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 80:80
    image: app:django
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:80
