# Generated by Django 3.2.10 on 2022-06-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrap',
            name='searching_device',
            field=models.CharField(default='', max_length=20, verbose_name='Девайс для поиска'),
        ),
        migrations.AlterField(
            model_name='relatedfile',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='slug',
            field=models.SlugField(default='fce063b159cf44d5b52d1ca62a864e45', max_length=150, unique=True, verbose_name='Ссылка'),
        ),
    ]
