# Generated by Django 3.2.10 on 2022-06-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0002_auto_20220616_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrap',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='slug',
            field=models.SlugField(default='2db567aec71d469b90cf6ca2ac62aad0', max_length=150, unique=True, verbose_name='Ссылка'),
        ),
    ]
