# Generated by Django 3.2.10 on 2022-06-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0004_auto_20220626_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='content',
            field=models.TextField(blank=True, default='', max_length=5500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='slug',
            field=models.SlugField(default='a275303ea0d94436abe183b98a5a06d9', max_length=150, unique=True, verbose_name='Ссылка'),
        ),
    ]
