# Generated by Django 3.2.10 on 2022-06-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0005_auto_20220627_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='slug',
            field=models.SlugField(default='eb71564d1f7a4633ad9cc6f996aeb55b', max_length=150, unique=True, verbose_name='Ссылка'),
        ),
    ]
