# Generated by Django 3.2.10 on 2022-06-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0007_auto_20220627_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrap',
            options={'ordering': ('-published',), 'verbose_name': 'Scraping', 'verbose_name_plural': 'Scrapings'},
        ),
        migrations.AlterField(
            model_name='scrap',
            name='slug',
            field=models.SlugField(default='5a381db592e64e119f72921507ce26d3', max_length=150, unique=True, verbose_name='Ссылка'),
        ),
    ]
