# Generated by Django 3.2.10 on 2022-06-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0008_auto_20220627_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrap',
            options={'ordering': ['-pk'], 'verbose_name': 'Scraping', 'verbose_name_plural': 'Scrapings'},
        ),
        migrations.AlterField(
            model_name='scrap',
            name='slug',
            field=models.SlugField(default='0a526f8700084a588537404a804253e6', max_length=150, unique=True, verbose_name='Ссылка'),
        ),
    ]
