# Generated by Django 3.2.10 on 2022-06-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0009_auto_20220627_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrap',
            options={'ordering': ['-published'], 'verbose_name': 'Scraping', 'verbose_name_plural': 'Scrapings'},
        ),
        migrations.AlterField(
            model_name='scrap',
            name='slug',
            field=models.SlugField(default='26a691863ecc4a04a48c5d2eed15880b', max_length=150, unique=True, verbose_name='Ссылка'),
        ),
    ]
