# Generated by Django 3.2.10 on 2022-07-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0010_auto_20220630_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='slug',
            field=models.SlugField(default='42b61362ce4d4d348ec58254afcb99ae', max_length=150, unique=True, verbose_name='Ссылка'),
        ),
    ]
