# Generated by Django 3.2.10 on 2022-07-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0012_auto_20220710_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='slug',
            field=models.SlugField(default='b0701f19395d4555a08e1747fdf66516', max_length=150, unique=True, verbose_name='Ссылка'),
        ),
    ]
